<?php

namespace Container8RHy4fG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFarmingCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\Cron\FarmingCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['.App\\Command\\Cron\\FarmingCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:cron:farming', ['app:cron:farming'], 'Test.', false, #[\Closure(name: 'App\\Command\\Cron\\FarmingCommand')] fn (): \App\Command\Cron\FarmingCommand => ($container->privates['App\\Command\\Cron\\FarmingCommand'] ?? $container->load('getFarmingCommandService')));
    }
}
