<?php

namespace Container8RHy4fG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestCommand' shared autowired service.
     *
     * @return \App\Command\TestCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TestCommand.php';

        $container->privates['App\\Command\\TestCommand'] = $instance = new \App\Command\TestCommand();

        $instance->setName('app:test');
        $instance->setAliases(['app:test']);
        $instance->setDescription('Test.');

        return $instance;
    }
}
