<?php

namespace Container5G3p5nR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFarmingCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\Cron\FarmingCommand' shared autowired service.
     *
     * @return \App\Command\Cron\FarmingCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Cron'.\DIRECTORY_SEPARATOR.'FarmingCommand.php';

        $container->privates['App\\Command\\Cron\\FarmingCommand'] = $instance = new \App\Command\Cron\FarmingCommand();

        $instance->setName('app:cron:farming');
        $instance->setAliases(['app:cron:farming']);
        $instance->setDescription('Test.');

        return $instance;
    }
}
