<?php

namespace Container5G3p5nR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSolanaServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Network\SolanaService' shared autowired service.
     *
     * @return \App\Service\Network\SolanaService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Network'.\DIRECTORY_SEPARATOR.'SolanaService.php';

        return $container->privates['App\\Service\\Network\\SolanaService'] = new \App\Service\Network\SolanaService(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['App\\Service\\TelegramService'] ?? $container->load('getTelegramServiceService')));
    }
}
