<?php

namespace Container5G3p5nR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTelegramServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TelegramService' shared autowired service.
     *
     * @return \App\Service\TelegramService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TelegramService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'illuminate'.\DIRECTORY_SEPARATOR.'macroable'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'Macroable.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Events'.\DIRECTORY_SEPARATOR.'HasEventDispatcher.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'Validator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'Http.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'CommandsHandler.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Traits'.\DIRECTORY_SEPARATOR.'HasContainer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Chat.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Commands.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'EditMessage.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Game.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Get.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Location.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Message.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Passport.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Payments.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Query.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Stickers.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Methods'.\DIRECTORY_SEPARATOR.'Update.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'irazasyed'.\DIRECTORY_SEPARATOR.'telegram-bot-sdk'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Api.php';

        return $container->privates['App\\Service\\TelegramService'] = new \App\Service\TelegramService(($container->privates['Telegram\\Bot\\Api'] ??= new \Telegram\Bot\Api($container->getEnv('TELEGRAM_BOT_TOKEN'))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->services['translator'] ?? $container->load('getTranslatorService')));
    }
}
