<?php

namespace Container5G3p5nR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTradingServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TradingService' shared autowired service.
     *
     * @return \App\Service\TradingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TradingService.php';

        return $container->privates['App\\Service\\TradingService'] = new \App\Service\TradingService(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['App\\Service\\TokenService'] ?? $container->load('getTokenServiceService')), ($container->privates['App\\Service\\Network\\SolanaService'] ?? $container->load('getSolanaServiceService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\PositionRepository'] ?? $container->load('getPositionRepositoryService')));
    }
}
