<?php

namespace Container5G3p5nR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTokenServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TokenService' shared autowired service.
     *
     * @return \App\Service\TokenService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TokenService.php';

        return $container->privates['App\\Service\\TokenService'] = new \App\Service\TokenService(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Repository\\TokenRepository'] ?? $container->load('getTokenRepositoryService')), ($container->privates['App\\Service\\Network\\SolanaService'] ?? $container->load('getSolanaServiceService')));
    }
}
