<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8RHy4fG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8RHy4fG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8RHy4fG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8RHy4fG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8RHy4fG\App_KernelDevDebugContainer([
    'container.build_hash' => '8RHy4fG',
    'container.build_id' => 'd8c5bb8e',
    'container.build_time' => 1723726396,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8RHy4fG');
